# Generated by Django 2.0.2 on 2018-02-11 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revisions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableTime',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
