# Generated by Django 2.0.2 on 2018-02-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_learning', models.BooleanField(default=False)),
                ('weight', models.FloatField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('seen', models.IntegerField()),
                ('first_learning_date', models.DateField()),
                ('second_learning_date', models.DateField()),
                ('third_learning_date', models.DateField()),
                ('fourth_learning_date', models.DateField()),
                ('fifth_learning_date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
