# Generated by Django 2.0.2 on 2018-02-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0002_auto_20180211_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fifth_learning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='first_learning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='fourth_learning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_learning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='third_learning_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
