# Generated by Django 2.0.2 on 2018-02-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0005_auto_20180211_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='book',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='item',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
