# Generated by Django 2.0.2 on 2018-02-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0006_auto_20180211_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='family',
            field=models.CharField(blank=True, choices=[('CHIRURGIE_ORALE', 'Chirurgie orale'), ('PARODONTOLOGIE', 'Parodontologie'), ('PEDODONTIE', 'Pedodontie'), ('OCE', 'OCE'), ('ORTHODONTIE', 'Orthodontie'), ('PROTHESE', 'Prothèse')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='book',
            field=models.CharField(blank=True, choices=[('CHIR_PARO', 'CHIR_PARO'), ('PEDO_ORTHO', 'PEDO_ORTHO'), ('OCE_PROTHESE', 'OCE_PROTHESE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
