# Generated by Django 2.0.2 on 2018-02-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0007_auto_20180211_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSeen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='fifth_learning_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='first_learning_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fourth_learning_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='second_learning_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='course',
            name='third_learning_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='family',
            field=models.CharField(blank=True, choices=[('CHIRURGIE_ORALE', 'Chirurgie orale'), ('PROTHESE', 'Prothèse'), ('ORTHODONTIE', 'Orthodontie'), ('PARODONTOLOGIE', 'Parodontologie'), ('PEDODONTIE', 'Pedodontie'), ('OCE', 'OCE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseseen',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revision.Course'),
        ),
    ]
