# Generated by Django 2.0.2 on 2018-02-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0008_auto_20180213_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('EASY PEASY', 'Easy Peasy'), ('SO SO', 'So so'), ('DIFFICULT', 'Difficult'), ('REALLY DIFFICULT', 'Really Difficult')], max_length=50, null=True),
        ),
    ]
