# Generated by Django 2.0.2 on 2018-02-18 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0009_course_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseseen',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
